/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-02-20 13:45:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import torverbook.web.constants.UrlRoutes;
import torverbook.web.constants.RequestAttributes;

public final class add_002dad_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"Java\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<!-- Charset & Responsiveness Metadata -->\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("<!-- StyleSheets -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/common.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/add-ad.css\" />\n");
      out.write("\n");
      out.write("<!-- Bootstrap CSS CDN -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- Google Fonts API CDN -->\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Montserrat:300,400,700,900&display=swap\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Comfortaa:300,400,700&display=swap\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<title>TorverBook - Add Ad</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<header>\n");
      out.write("\t\t<h1 id=\"header-title\">TorverBook</h1>\n");
      out.write("\t</header>\n");
      out.write("\t<div id=\"content-container\">\n");
      out.write("\t\t<div class=\"row main-panels-container\">\n");
      out.write("\t\t\t<panel class=\"left-panel col-lg-3\"> <a href=\"/dashboard\">\n");
      out.write("\t\t\t\t<button id=\"home-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-home\" /></em> Home\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> <a href=\"/settings\">\n");
      out.write("\t\t\t\t<button id=\"settings-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-gear\" /></em> Settings\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> <a href=\"/add-ad\">\n");
      out.write("\t\t\t\t<button class=\"active\" id=\"add-ad-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-plus\" /></em> Add Ad\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> <a href=\"/personal-ads\">\n");
      out.write("\t\t\t\t<button id=\"my-ads-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-bookmark\" /></em> My Ads\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> <a href=\"/personal-reviews\">\n");
      out.write("\t\t\t\t<button id=\"my-reviews-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-th-list\" /></em> My Reviews\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> <a href=\"/favourite\">\n");
      out.write("\t\t\t\t<button id=\"favourites-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-star\" /></em> Favourite List\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> <a href=\"/logout\">\n");
      out.write("\t\t\t\t<button id=\"logout-btn\">\n");
      out.write("\t\t\t\t\t<em class=\"fa fa-sign-out-alt\" /></em> Logout\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</a> </panel>\n");
      out.write("\t\t\t<panel class=\"central-panel col-lg-6\">\n");
      out.write("\t\t\t<form method=\"POST\" action=\"");
      out.print(UrlRoutes.ADD_AD_FULL_URL);
      out.write("\">\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-title-input\">Ad Title</label> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"ad-title-input\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_TITLE_ATTRIBUTE_NAME);
      out.write("\"\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Java For Dummies\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-description-input\">Ad Description</label>\n");
      out.write("\t\t\t\t\t<textarea class=\"form-control\" id=\"ad-description-input\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_DESCRITPION_ATTRIBUTE_NAME);
      out.write("\"></textarea>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-type-input\">Type</label> <select\n");
      out.write("\t\t\t\t\t\tclass=\"custom-select custom-select-sm\" id=\"ad-type-input\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_TYPE_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<option>SALE</option>\n");
      out.write("\t\t\t\t\t\t<option>EXCHANGE</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-price-input\">Price</label> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"ad-price-input\" placeholder=\"($) 35\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_PRICE_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-quantity-input\">Quantity</label> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"ad-quantity-input\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_QUANTITY_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-category-input\">College Course</label> <select\n");
      out.write("\t\t\t\t\t\tclass=\"custom-select custom-select-sm\" id=\"ad-category-input\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_CATEGORY_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<option>ALGORITHMS</option>\n");
      out.write("\t\t\t\t\t\t<option>MATH</option>\n");
      out.write("\t\t\t\t\t\t<option>HISTORY</option>\n");
      out.write("\t\t\t\t\t\t<option>GEOMETRY</option>\n");
      out.write("\t\t\t\t\t\t<option>LAW</option>\n");
      out.write("\t\t\t\t\t\t<option>ECONOMY</option>\n");
      out.write("\t\t\t\t\t\t<option>LITERATURE</option>\n");
      out.write("\t\t\t\t\t\t<option>PHILOSOPHY</option>\n");
      out.write("\t\t\t\t\t\t<option>PHYSICS</option>\n");
      out.write("\t\t\t\t\t\t<option>COMPUTER_SCIENCE</option>\n");
      out.write("\t\t\t\t\t\t<option>CHEMISTRY</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-highlight-input\">Highlight</label> <select\n");
      out.write("\t\t\t\t\t\tclass=\"custom-select custom-select-sm\" id=\"ad-highlight-input\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_HIGHLIGHT_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<option>BASE</option>\n");
      out.write("\t\t\t\t\t\t<option>MEDIUM</option>\n");
      out.write("\t\t\t\t\t\t<option>SUPER</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-from-date-input\">From:</label> <input type=\"date\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"ad-from-date-input\" placeholder=\"\"\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(LocalDate.now().toString());
      out.write("\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_HIGHLIGHT_FROM_DATE_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label for=\"ad-to-date-input\">To:</label> <input type=\"date\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"ad-to-date-input\" placeholder=\"\"\n");
      out.write("\t\t\t\t\t\tname=\"");
      out.print(RequestAttributes.AD_HIGHLIGHT_TO_DATE_ATTRIBUTE_NAME);
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<button class=\"btn btn-light btn-md\">Add Ad</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t</panel>\n");
      out.write("\n");
      out.write("\t\t\t<panel class=\"right-panel col-lg-3\">\n");
      out.write("\t\t\t<div class=\"no-messages-container\">\n");
      out.write("\t\t\t\t<em class=\"fa fa-envelope-open fa-5x\"></em>\n");
      out.write("\t\t\t\t<h1>No messages yet..</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</panel>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Bootstrap JS CDN -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\"\n");
      out.write("\tintegrity=\"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\n");
      out.write("\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<!-- FontAwesome JS CDN -->\n");
      out.write("<script src=\"https://kit.fontawesome.com/8526e38f8c.js\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
